### ISSUE TITLE
[JOSS review] Suggestions for installation docs

### ISSUE THREAD

**Issue by mstimberg** [flintproject/Flint#15]
Issue opened as part of the JOSS review (openjournals/joss-reviews#2331)

I was able to compile the software from source given the instructions in `INSTALL.org` on Ubuntu 18.04.

I think this document should also mention how to run the test suite (if I am not mistaken, running `make check` in `posix/var/sequential-version/test` will do it).

As a minor suggestion: I think it should more clearly mention that before running the build commands, you have to install the prerequisites for your platform. Currently it reads a bit odd: "This is the command to build it: .... Before running the above command, you have to do this: ..."

**Comment by tabe** [comment]
Rearranged INSTALL.org with ec28ff2d95bc3fd9fb961083887116f715c73e15, it now explains how to run tests after building.

**Comment by mstimberg** [comment]
Thanks, this is looking all good from my side now and installing it from source worked flawlessly on Ubuntu 18.04.
