### ISSUE TITLE
Publish community guidelines

### ISSUE THREAD

**Issue by tabe** [flintproject/Flint#21]
It would be helpful for potential contributors to have Flint's community guidelines in the official site and in documentation.
Suggested in <https://github.com/openjournals/joss-reviews/issues/2331#issuecomment-674147285>.

**Comment by dawbarton** [comment]
I've added a few comments on the commit in https://github.com/flintproject/Flint/commit/9029aecc7433040f405c5db501b2f6686335f150#comments

Overall it looks good.
